apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail
  template:
    metadata:
      labels:
        app: retail
    spec:
      containers:
        - name: retail-app
          image: retail-app:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: retail-service
spec:
  type: LoadBalancer
  selector:
    app: retail
  ports:
    - port: 8080
      targetPort: 8080