apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:2.4   # or your custom image
          ports:
            - containerPort: 80
